### PR TITLE
ch-configuring-eslint: configuringeslint

### PR DESCRIPTION
**Pull request by tigthor**
### What does this PR do?
- Making eslint configuration
- Following guidelines as given on pivot tracker
### Description of Task to be completed?
N/A
### How should this be manually tested?
N/A
### Any background context you want to provide?
N/A
### What are the relevant pivotal tracker stories?
N/A 
### Screenshot (if appropriate) 
N/A

[finish #175494029]

### CODE REVIEW

**Comment by eustacheAki** [comment]
well done

**Comment by Hyacinthe396** [comment]
Nice Job, courage

**Review by EngMutabazi — COMMENTED** [review]
good!!

**Comment by Niyonsengaeric** [comment]
LGTM

**Pull request merged**
